export const LANG_EXT: Record<string, string> = {
  typescript: 'ts',
  javascript: 'js',
  python3: 'py',
  python: 'py',
  java: 'java',
  cpp: 'cpp',
  c: 'c',
  csharp: 'cs',
  golang: 'go',
  kotlin: 'kt',
  swift: 'swift',
  rust: 'rs',
  scala: 'scala',
  ruby: 'rb',
  php: 'php',
  mysql: 'sql',
};

export const DIFFICULTY_ICON: Record<string, string> = {
  Easy: '🟢',
  Medium: '🟡',
  Hard: '🔴',
};

// Ordered list of categories shown in the README
export const CATEGORY_ORDER = [
  'Array',
  'String',
  'Hash Table',
  'Two Pointers',
  'Sliding Window',
  'Linked List',
  'Stack & Queue',
  'Binary Search',
  'Tree',
  'Graph',
  'Dynamic Programming',
  'Backtracking',
  'Math',
  'Design',
  'Database',
  'Other',
];

// Maps LeetCode tag names to a README category (first match wins)
export const TAG_TO_CATEGORY: Record<string, string> = {
  'Array': 'Array',
  'Matrix': 'Array',
  'String': 'String',
  'Hash Table': 'Hash Table',
  'Two Pointers': 'Two Pointers',
  'Sliding Window': 'Sliding Window',
  'Linked List': 'Linked List',
  'Stack': 'Stack & Queue',
  'Queue': 'Stack & Queue',
  'Monotonic Stack': 'Stack & Queue',
  'Binary Search': 'Binary Search',
  'Tree': 'Tree',
  'Binary Tree': 'Tree',
  'Binary Search Tree': 'Tree',
  'Depth-First Search': 'Tree',
  'Breadth-First Search': 'Tree',
  'Graph': 'Graph',
  'Union Find': 'Graph',
  'Topological Sort': 'Graph',
  'Dynamic Programming': 'Dynamic Programming',
  'Memoization': 'Dynamic Programming',
  'Backtracking': 'Backtracking',
  'Math': 'Math',
  'Bit Manipulation': 'Math',
  'Recursion': 'Math',
  'Design': 'Design',
  'Database': 'Database',
};
